In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5,7,8])
a # 1d array

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a # 2d array

In [ ]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]] ])
a # 3d array

In [ ]:
a.shape

Above array can be interpreted as 2 stacked list of 3 rows and 4 columns

In [ ]:
a=np.array([ [ [1,2],[3,4] ] ,[[5,6],[7,8]]  ])
a

In [ ]:
a=np.arange(0,20,1)
a# will create a array with number between 0 and 20 with gap of 1 

In [ ]:
a=np.linspace(0,20,30)
a # linespace is like arrange but it will create array between 0 and 20 with 30 values

In [ ]:
avg=np.mean(a)#mean
avg

In [ ]:
a=np.array([2,3,1,4,5,6,8,0])
a

In [ ]:
med =np.median(a)
med

In [48]:
var = np.var(a)
var

6.234375

In [49]:
std = np.std(a)
std

2.496873044429772

In [52]:
a=np.array([1,4,5,6,7,8,9,12,14,14,18])
max=np.max(a)
min=np.min(a)
max,min

(18, 1)

In [54]:
a=np.array([9,1,35,6,2,8,10,21,4])
sort = np.sort(a)
sort

array([ 1,  2,  4,  6,  8,  9, 10, 21, 35])

In [55]:
np.argmax(a)

2

In [56]:
np.argmin(a)

1

In [58]:
np.sum(a)

96

In [62]:
a=np.array([2,2,2,2,3,3,4,5,6,7,8,8,8])
unique,counts=np.unique(a,return_counts=True)
unique,counts

(array([2, 3, 4, 5, 6, 7, 8]), array([4, 2, 1, 1, 1, 1, 3], dtype=int64))

In [68]:
a=np.random.rand(1,5)
a

array([[0.36649832, 0.90744214, 0.98357732, 0.59536415, 0.34339147]])

In [72]:
a=np.random.randn(1,10)
a

array([[ 0.06947588,  0.98714931,  0.1514831 , -1.28785198,  0.15964506,
         0.53702765, -0.45409533, -2.59414878,  0.05154361, -0.94173138]])

In [81]:
a=np.random.randint(1,9)
a

1

In [90]:
a=np.array([1,2,3,4,5,6,7,8,9])
np.where(a>3,True,False) # where condition

array([False, False, False,  True,  True,  True,  True,  True,  True])