In [2]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [6]:
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a.ndim #dimesnion of array number of dimension

1

In [8]:
a.shape #shape of a numpy array

(9,)

In [10]:
b=np.array([[1,2,3,4,5,6,7],[9,8,7,6,5,4,3]])

In [11]:
b

array([[1, 2, 3, 4, 5, 6, 7],
       [9, 8, 7, 6, 5, 4, 3]])

In [12]:
a.dtype

dtype('int32')

In [13]:
b.dtype

dtype('int32')

In [14]:
b[1,2] # first row and second column (index starts from 0)

7

In [15]:
b[:,1]

array([2, 8])

In [16]:
b[0,1:7:1]

array([2, 3, 4, 5, 6, 7])

In [17]:
b[0,1:7:2] # start:end:step_size

array([2, 4, 6])

In [18]:
c=np.array([[1,2,3],[3,4,5],[6,7,8]])

In [19]:
c


array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
c[[0,1,2]]

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
c[:,1:]

array([[2, 3],
       [4, 5],
       [7, 8]])

In [30]:
c.shape

(3, 3)

In [42]:
c[[0,1,2],1] #all rows and first column 

array([2, 4, 7])

In [45]:
c[[0,1],[2,1]] #0 and 1 row and 2 and 1 element of it 

array([3, 4])

In [46]:
c[[0,1],[2,1]]=[11,12] #changing the element of numoy array

In [47]:
c

array([[ 1,  2, 11],
       [ 3, 12,  5],
       [ 6,  7,  8]])

In [49]:
np.zeros((1,4)) #array of all zero elemt with 1 row and 4 elemrnt in it 

array([[0., 0., 0., 0.]])

In [51]:
d=np.zeros((4,5,6)) # first tells number of matrix and second and third
                    #element tells rows and column in each element


In [52]:
d

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [57]:
e=np.ones((2,3,4),dtype='int32') #changed type to int32

In [58]:
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [59]:
f = np.full((2,3,4),8)  #making an array of 8 , it takes two parameter first one 
                        #shape of array and second the number for which array is required

In [60]:
f


array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [61]:
np.full_like(a,2) # inherit the shape of existing array 

array([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [62]:
np.random.rand(2,3,4) #an array with random values 

array([[[0.5992623 , 0.83514851, 0.17676077, 0.98896495],
        [0.38588311, 0.65243103, 0.42871185, 0.54196274],
        [0.29978586, 0.98997779, 0.09473384, 0.33652983]],

       [[0.04571965, 0.02000497, 0.96637181, 0.439886  ],
        [0.11320787, 0.97235098, 0.38541719, 0.78729119],
        [0.54893326, 0.94422295, 0.99110421, 0.86686031]]])

In [67]:
np.random.rand(2,6,7)

array([[[3.80042885e-01, 4.39716511e-01, 4.71981584e-01, 6.33525723e-02,
         1.99556459e-01, 2.61379898e-01, 8.55842769e-02],
        [5.19867176e-01, 9.82494293e-01, 3.15071457e-01, 3.83084467e-01,
         8.27828049e-01, 3.37978741e-01, 3.81602594e-01],
        [4.96725646e-01, 3.44958362e-01, 4.41861994e-02, 9.20546070e-01,
         5.77125916e-01, 8.51761187e-01, 1.62835690e-02],
        [3.90847097e-03, 9.29464646e-01, 9.40342148e-01, 1.22752851e-01,
         2.27264426e-02, 1.78731733e-01, 7.30305275e-01],
        [6.56026230e-01, 6.55098127e-01, 4.38123189e-02, 9.85292678e-01,
         4.24604252e-01, 3.19080467e-01, 5.46910532e-01],
        [9.76154577e-01, 5.02351835e-01, 6.39886238e-01, 8.31409795e-01,
         9.84623959e-02, 9.49071207e-02, 4.89006093e-01]],

       [[4.69865286e-01, 8.22236538e-01, 1.39162673e-01, 3.56542171e-01,
         5.34125333e-02, 7.68503460e-01, 6.74080147e-01],
        [8.33928683e-01, 1.72572796e-01, 5.43397549e-01, 5.42354286e-01,
        

In [70]:
i = np.identity(5)

In [71]:
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
i = np.identity(5 , dtype='int32') # identity is used to create identity array 

In [74]:
i

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [85]:
#repeat an array 
a=np.array([[1,2,3]]) # first create an array
b=np.repeat(a,3,axis=0) #repeat is used to create a repeated array
b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [89]:
np.random.rand(2,3,4)

array([[[0.9773766 , 0.0182469 , 0.51845103, 0.15223403],
        [0.35141962, 0.28290022, 0.72412904, 0.07106751],
        [0.55416718, 0.52395027, 0.22540659, 0.7830445 ]],

       [[0.76749642, 0.53445503, 0.7503773 , 0.74795914],
        [0.66000359, 0.68750468, 0.16660287, 0.95974258],
        [0.29073799, 0.02915932, 0.52124146, 0.42028358]]])

In [92]:
#copying the numpy 
a= np.array([1,2,3])
b=a
b[1]=20
print(a)
#here we have changed the value of b but value of a is also changed 

[ 1 20  3]


In [93]:
#another way of preventing above 
a=np.array([1,2,3])
b=a.copy()
b[1]=20
print(a)


[1 2 3]


In [94]:
a

array([1, 2, 3])

In [98]:
a+2 #add two to every component of numpy


array([3, 4, 5])

In [99]:
a-2 #subtract two to every component of numpy


array([-1,  0,  1])

In [100]:
a*2  #multiply two to every component of numpy


array([2, 4, 6])

In [101]:
a/2 #divide two to every component of numpy

array([0.5, 1. , 1.5])

In [102]:
np.cos(a) #cosine of a 

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [103]:
np.sin(a) # sine of a 

array([0.84147098, 0.90929743, 0.14112001])

In [107]:
#linear algebra
a=np.ones((2,3))
print(a)
b=np.full((3,4),3)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


array([[9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [108]:
a.max()

1.0

In [109]:
b.min()

3

In [110]:
a.sum()

6.0

In [111]:
b.sum()

36